# Generated by Django 4.0.5 on 2022-06-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeHeroImage', models.CharField(max_length=10000)),
                ('homeHeroImageContent', models.TextField(max_length=10000)),
                ('homePageAbout', models.TextField(max_length=10000)),
                ('homePageAboutImage', models.ImageField(default='1.png', upload_to='')),
                ('homeOurStrengthIcon', models.CharField(help_text='Enter ; after each icon class name', max_length=10000)),
                ('homeOurStrengthText', models.CharField(help_text='Enter ; after each icon class name', max_length=10000)),
                ('homeProductsImage', models.ImageField(default='1.png', upload_to='')),
                ('homeProductsImageIndustry', models.CharField(max_length=10000)),
                ('homeProductsImageDescription', models.CharField(max_length=10000)),
                ('homeProductsAboutHeading', models.TextField(max_length=10000)),
                ('blogTitle', models.CharField(max_length=2000)),
                ('blogAuthor', models.CharField(max_length=200)),
                ('blogDate', models.CharField(max_length=200)),
                ('blogContent', models.TextField(max_length=20000)),
                ('blogImage', models.CharField(max_length=2000)),
            ],
        ),
    ]
