# Generated by Django 4.0.5 on 2022-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='homeTestimonialAuthor',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='homeTestimonialContent',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='homeTestimonialDesignation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='homeTestimonialImage',
            field=models.ImageField(default='2.png', upload_to=''),
        ),
    ]
