# Generated by Django 4.0.5 on 2022-06-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0003_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='formImageLink',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
