# Generated by Django 4.0.5 on 2022-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0006_agrochemicalsportfolio_chemicalportfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientelePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroImageLink', models.CharField(max_length=10000)),
            ],
        ),
    ]
