# Generated by Django 4.0.5 on 2022-06-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0007_clientelepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroImageLink', models.CharField(max_length=10000)),
                ('blogTitle', models.CharField(max_length=2000)),
                ('blogAuthor', models.CharField(max_length=200)),
                ('blogDate', models.CharField(max_length=200)),
                ('blogContent', models.TextField(max_length=20000)),
                ('blogImage', models.CharField(max_length=2000)),
            ],
        ),
    ]
