# Generated by Django 4.0.5 on 2022-06-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0009_bloghero_remove_blogpage_heroimagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroimageLink', models.CharField(max_length=3000)),
                ('aboutParagraph', models.TextField(max_length=5000)),
                ('aboutParagraphImage', models.ImageField(default='logo.png', upload_to='')),
                ('companyEstablishedYear', models.CharField(max_length=200)),
                ('companyEmployees', models.CharField(max_length=2000)),
                ('companyProjects', models.CharField(max_length=2000)),
                ('companyAnnualTurnover', models.CharField(max_length=2000)),
                ('vision', models.CharField(max_length=5000)),
                ('mission', models.CharField(help_text='Enter ; After every Mission Point i.e abc;bcd', max_length=5000)),
                ('corporateValue', models.CharField(max_length=5000)),
                ('missionvissionBackground', models.TextField(max_length=3000)),
                ('clientBackground', models.TextField(max_length=3000)),
                ('companyValuesBackground', models.TextField(max_length=3000)),
                ('teamBackground', models.TextField(max_length=3000)),
                ('teamMemberImage', models.CharField(max_length=2000)),
                ('teamMemberName', models.CharField(max_length=200)),
                ('teamMemberDesignation', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='bloghero',
            name='heroImageLink',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
