# Generated by Django 4.0.5 on 2022-06-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0010_aboutpage_alter_bloghero_heroimagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamMemberImage', models.CharField(max_length=2000)),
                ('teamMemberName', models.CharField(max_length=200)),
                ('teamMemberDesignation', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='teamMemberDesignation',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='teamMemberImage',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='teamMemberName',
        ),
    ]
