# Generated by Django 4.0.5 on 2022-06-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0011_team_remove_aboutpage_teammemberdesignation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='corporateValue',
            field=models.CharField(help_text='Enter ; After every Mission Point i.e abc;bcd', max_length=5000),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision',
            field=models.CharField(help_text='Enter ; After every Mission Point i.e abc;bcd', max_length=5000),
        ),
    ]
