# Generated by Django 4.0.5 on 2022-06-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0012_alter_aboutpage_corporatevalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeHeroImage', models.CharField(max_length=10000)),
                ('homeHeroImageHeading', models.TextField(max_length=10000)),
                ('homeHeroImageContent', models.TextField(max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blogAuthor',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blogContent',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blogDate',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blogImage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blogTitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='homeHeroImage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='homeHeroImageContent',
        ),
    ]
