# Generated by Django 4.0.5 on 2022-06-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0014_testimonial_remove_homepage_hometestimonialauthor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='homeOurStrengthHeading',
            field=models.CharField(help_text='Enter ; after each icon class name', max_length=10000, null=True),
        ),
    ]
