# Generated by Django 4.0.5 on 2022-06-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0016_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroimageLink', models.CharField(max_length=3000)),
                ('addedServicesPoints', models.CharField(help_text='Enter ; After every Mission Point i.e abc;bcd', max_length=10000)),
                ('servicesOneImage', models.CharField(max_length=2000)),
                ('servicesRowImage', models.CharField(max_length=2000)),
            ],
        ),
    ]
