# Generated by Django 4.0.5 on 2022-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0017_servicespage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespage',
            name='servicesRowImage',
        ),
        migrations.AddField(
            model_name='servicespage',
            name='servicesThreeImage',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='servicespage',
            name='servicesTwoImage',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
