# Generated by Django 4.0.5 on 2022-06-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0018_remove_servicespage_servicesrowimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeProductsImage', models.ImageField(default='1.png', upload_to='')),
                ('homeProductsImageIndustry', models.CharField(max_length=10000)),
                ('homeProductsImageDescription', models.CharField(max_length=10000)),
                ('homeProductsAboutHeading', models.TextField(max_length=10000)),
                ('homeProductsDescription', models.TextField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeOurStrengthIcon', models.CharField(max_length=10000)),
                ('homeOurStrengthHeading', models.CharField(max_length=10000, null=True)),
                ('homeOurStrengthText', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='homeProductsImageDescription',
            new_name='homeTestimonialBackground',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='homeOurStrengthHeading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='homeOurStrengthIcon',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='homeOurStrengthText',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='homeProductsAboutHeading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='homeProductsDescription',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='homeProductsImage',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='homeProductsImageIndustry',
        ),
        migrations.AddField(
            model_name='homepage',
            name='homeStrengthBackground',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
