# Generated by Django 4.0.5 on 2022-06-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0019_homeproducts_strength_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeproducts',
            old_name='homeProductsImage',
            new_name='homeProductOneImage',
        ),
        migrations.AddField(
            model_name='homeproducts',
            name='homeProductThreeImage',
            field=models.ImageField(default='1.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='homeproducts',
            name='homeProductTwoImage',
            field=models.ImageField(default='1.png', upload_to=''),
        ),
    ]
