# Generated by Django 4.0.5 on 2022-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0020_rename_homeproductsimage_homeproducts_homeproductoneimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeproducts',
            old_name='homeProductsDescription',
            new_name='civilProductDescription',
        ),
        migrations.RenameField(
            model_name='homeproducts',
            old_name='homeProductOneImage',
            new_name='civilProductImage',
        ),
        migrations.RenameField(
            model_name='homeproducts',
            old_name='homeProductsImageDescription',
            new_name='civilProductImageDescription',
        ),
        migrations.RenameField(
            model_name='homeproducts',
            old_name='homeProductThreeImage',
            new_name='electricalProductImage',
        ),
        migrations.RenameField(
            model_name='homeproducts',
            old_name='homeProductsImageIndustry',
            new_name='electricalProductImageDescription',
        ),
        migrations.RenameField(
            model_name='homeproducts',
            old_name='homeProductTwoImage',
            new_name='mechanicalProductImage',
        ),
        migrations.RemoveField(
            model_name='homeproducts',
            name='homeProductsAboutHeading',
        ),
        migrations.AddField(
            model_name='homeproducts',
            name='electricalProductDescription',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='homeproducts',
            name='mechanicalProductDescription',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='homeproducts',
            name='mechanicalProductImageDescription',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
