# Generated by Django 4.0.5 on 2022-06-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0021_rename_homeproductsdescription_homeproducts_civilproductdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strength',
            name='homeOurStrengthCard',
            field=models.CharField(default='strength-card', max_length=300),
        ),
    ]
