# Generated by Django 4.0.5 on 2022-06-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divyaChemicalsWeb', '0022_strength_homeourstrengthcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='mechanicalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanicalProductImage', models.ImageField(default='logo.png', upload_to='')),
                ('mechanicalProductImageName', models.CharField(max_length=2000)),
                ('mechanicalProductsImageDescription', models.TextField(max_length=2000,null=True,blank=True)),
            ],
        ),
    ]
