from django.contrib import admin
from divyaChemicalsWeb.models import otherMaintananceProducts,aboutPage,civilProducts,electricalProducts,homeHeroImage,homePage,blogPage,blogHero,clientelePage,contactPage,contactQuery,agrochemicalsPortfolio,  chemicalPortfolio,  engieeringAutomobilesPortfolio, fertilizerPortfolio, foodPharmaPortfolio, glassCeramicPortfolio,homeProducts, metalPortfolio,mechanicalProducts, oilGasPortfolio, powerWindPortfolio, services,servicesPage,strength,testimonial, team,tyrePortfolio


admin.site.register(aboutPage)
admin.site.register(homePage)
admin.site.register(homeHeroImage)
admin.site.register(contactPage)
admin.site.register(contactQuery)
admin.site.register(clientelePage)
admin.site.register(chemicalPortfolio)
admin.site.register(foodPharmaPortfolio)
admin.site.register(homeProducts)
admin.site.register(powerWindPortfolio)
admin.site.register(agrochemicalsPortfolio)
admin.site.register(mechanicalProducts)
admin.site.register(civilProducts)
admin.site.register(electricalProducts)
admin.site.register(metalPortfolio)
admin.site.register(fertilizerPortfolio)
admin.site.register(glassCeramicPortfolio)
admin.site.register(engieeringAutomobilesPortfolio)
admin.site.register(oilGasPortfolio)
admin.site.register(tyrePortfolio)
admin.site.register(strength)
admin.site.register(services)
admin.site.register(servicesPage)
admin.site.register(team)
admin.site.register(testimonial)
admin.site.register(blogPage)
admin.site.register(blogHero)
admin.site.register(otherMaintananceProducts)